services:
  # === 公共基础设施 ===
  redis:
    image: redis:alpine
    container_name: se-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - search-net
  postgres:
    image: postgres:15-alpine
    container_name: se-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: search_engine
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - search-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d search_engine"]
      interval: 5s
      timeout: 5s
      retries: 5


  compute-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: search-compute:v1
    volumes:
      - .:/app
    networks:
      - search-net
    environment:
      - REDIS_HOST=redis
    command: ["python", "--version"]

  pr-controller:
    image: search-compute:v1
    container_name: pr-controller
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - search-net
    depends_on:
      - redis

    command: ["python", "compute/pagerank/controller.py"]

  pr-worker:
    image: search-compute:v1
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    networks:
      - search-net
    depends_on:
      - redis
      - pr-controller
    command: ["python", "compute/pagerank/worker.py"]
  backend:
    build:
      context: .
      dockerfile: serving/Dockerfile
    image: search-backend:v1
    container_name: se-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - search-net
    restart: always

  eval-node:
    build:
      context: ./evaluation
      dockerfile: Dockerfile
    image: search-eval:v1
    container_name: evaluation
    volumes:
      - .:/app
      - ./data:/app/data

    environment:
        - REDIS_HOST=redis
        - PG_HOST=postgres
        - PG_USER=admin
        - PG_PASS=password
        - PG_DB=search_engine
    networks:
      - search-net
    depends_on:
      - postgres
      - redis
    profiles: [ "tools" ]
    command: [ "python", "--version" ]

  frontend:
    build: ./frontend
    image: search-frontend:v1
    container_name: se-frontend
    ports:
      - "8501:8501"
    networks:
      - search-net
    depends_on:
      - backend
    restart: always
networks:
  search-net:
    driver: bridge

volumes:
  redis_data:
  pg_data: